import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { Link, NavLink, useNavigate } from "react-router-dom";
import { ThemeToggle } from "../theme";
function authed() {
    return Boolean(localStorage.getItem("token"));
}
export function Navbar() {
    const nav = useNavigate();
    const ok = authed();
    return (_jsx("header", { className: "navbar", children: _jsxs("div", { className: "navbar__inner", children: [_jsxs(Link, { to: "/", className: "navbar__brand", "aria-label": "Nebula9 home", children: [_jsx("span", { className: "navbar__logo", children: "N9" }), _jsxs("span", { className: "navbar__titles", children: [_jsx("strong", { className: "navbar__name", children: "Nebula9" }), _jsx("span", { className: "navbar__tagline", children: "Financial Insights" })] }), _jsx("span", { className: "pill navbar__pill", children: "edu \u00B7 simulated" })] }), _jsx("nav", { className: "navbar__nav", "aria-label": "Primary", children: ok ? (_jsx(NavLink, { to: "/", className: ({ isActive }) => "nav-link" + (isActive ? " nav-link--active" : ""), end: true, children: "Dashboard" })) : (_jsx(_Fragment, { children: _jsx(NavLink, { to: "/login", className: ({ isActive }) => "nav-link" + (isActive ? " nav-link--active" : ""), children: "Sign in" }) })) }), _jsxs("div", { className: "navbar__actions", children: [_jsx(ThemeToggle, {}), ok ? (_jsx("button", { type: "button", className: "btn btn-nav-signout", onClick: () => {
                                localStorage.removeItem("token");
                                nav("/login");
                            }, children: "Sign out" })) : null] })] }) }));
}
export function Footer() {
    const year = new Date().getFullYear();
    return (_jsxs("footer", { className: "site-footer", children: [_jsxs("div", { className: "site-footer__inner", children: [_jsxs("div", { className: "site-footer__col site-footer__intro", children: [_jsxs("div", { className: "site-footer__brand", children: [_jsx("span", { className: "navbar__logo navbar__logo--footer", children: "N9" }), _jsx("strong", { children: "Nebula9" })] }), _jsx("p", { className: "site-footer__text", children: "Educational hiring demo: simulated markets, grounded insights, and live-style streaming \u2014 not a brokerage or advisory service." })] }), _jsxs("div", { className: "site-footer__col", children: [_jsx("h3", { className: "site-footer__heading", children: "Product" }), _jsxs("ul", { className: "site-footer__list", children: [_jsx("li", { children: _jsx(Link, { to: "/", children: "Dashboard" }) }), _jsx("li", { children: _jsx(Link, { to: "/login", children: "Sign in & register" }) })] })] }), _jsxs("div", { className: "site-footer__col", children: [_jsx("h3", { className: "site-footer__heading", children: "Compliance" }), _jsxs("ul", { className: "site-footer__list", children: [_jsx("li", { children: _jsx("span", { className: "site-footer__static", children: "Not investment advice" }) }), _jsx("li", { children: _jsx("span", { className: "site-footer__static", children: "Synthetic or delayed data" }) }), _jsx("li", { children: _jsx("span", { className: "site-footer__static", children: "No orders or custody" }) })] })] }), _jsxs("div", { className: "site-footer__col", children: [_jsx("h3", { className: "site-footer__heading", children: "Architecture" }), _jsxs("ul", { className: "site-footer__list site-footer__list--muted", children: [_jsx("li", { children: "TimescaleDB time-series" }), _jsx("li", { children: "WebSocket price stream" }), _jsx("li", { children: "JWT sessions \u00B7 optional OAuth" })] })] })] }), _jsx("div", { className: "site-footer__bar", children: _jsxs("p", { className: "site-footer__copy", children: ["\u00A9 ", year, " Nebula9 demo \u00B7 Past performance does not guarantee future results."] }) })] }));
}
